# Generated by Django 5.1.3 on 2024-11-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='middle_name',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
